#!/bin/sh

alias ls='ls --color=auto'
alias la='ls -a --color=auto'
alias ll='ls -al --color=auto'
alias grep='grep --color=auto'
alias vim='nvim'


alias gs='git status'
alias gl='git log'
alias glp='git log -p'
alias glg='git log --graph'

alias gcl='git clone'
alias gf='git fetch'

alias gb='git branch'
alias gba='git branch --all'
alias gch='git checkout'

alias gm='git merge'
alias gp='git pull'
alias gpu='git push'

alias gc='git commit'
alias gca='git commit --amend'
alias gcm='git commit -m'

alias ga='git add'
alias gap='git add --patch'
alias grm='git rm'
alias gr='git restore'
alias grs='git restore --staged'

alias gst='git stash'

alias gd='git diff'
alias gdh='git diff HEAD'
alias gds='git diff --cached'
