pcall(require, 'impatient')
require 'user.plugins'
require 'user.settings'
require 'user.keybinds'
require 'user.treesitter'
require 'user.mason'
-- require 'user.lsp'
require 'user.cmp'
require 'user.indentblankline'
require 'user.lualine'
require 'user.bufferline'
require 'user.autopair'
require 'user.telescope'
require 'user.nvimtree'
require 'user.colorscheme'
require 'user.comment'
require 'user.toggleterm'
